import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import { getAuth, signInAnonymously, onAuthStateChanged } from "firebase/auth";
import { app } from "@/lib/firebase"; // or wherever you initialized firebase
import { FirebaseAuthProvider } from "@/contexts/FirebaseAuthContext";

const auth = getAuth(app);

onAuthStateChanged(auth, (user) => {
  if (!user) {
    signInAnonymously(auth)
      .then(() => console.log("✅ Signed in anonymously"))
      .catch((error) => console.error("❌ Sign-in error:", error))
  } else {
    console.log("✅ Already signed in:", user.uid)
  }
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Queen Of Acorns",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FirebaseAuthProvider>
        {children}
        </FirebaseAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
